# Generated by Django 3.1.2 on 2020-10-21 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_enrolled', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Instutution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('typ', models.CharField(choices=[('Private', 'Private'), ('Public', 'Public')], max_length=50)),
                ('key', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('University', 'University'), ('TVET Colleage', 'TVET Colleage')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Degree', 'Degree'), ('Diploma', 'Diploma'), ('Certificate', 'Certificate')], max_length=30)),
                ('cutoff_points', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('school', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('points', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProgrammeChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instutution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.instutution')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.programme')),
            ],
        ),
        migrations.AddField(
            model_name='programme',
            name='instutution',
            field=models.ManyToManyField(through='student.ProgrammeChoice', to='student.Instutution'),
        ),
        migrations.AddField(
            model_name='programme',
            name='students',
            field=models.ManyToManyField(through='student.Enrollment', to='student.Student'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='Student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='instutution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.instutution'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.programme'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('Student', 'programme', 'instutution')},
        ),
    ]
