# Generated by Django 3.1.2 on 2020-10-23 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('typ', models.CharField(choices=[('Private', 'Private'), ('Public', 'Public')], max_length=50)),
                ('key', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('University', 'University'), ('TVET Colleage', 'TVET Colleage')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Degree', 'Degree'), ('Diploma', 'Diploma'), ('Certificate', 'Certificate')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ProgrammeChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cutoff_points', models.DecimalField(decimal_places=2, max_digits=10)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.institution')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.programme')),
            ],
        ),
        migrations.AddField(
            model_name='programme',
            name='institution',
            field=models.ManyToManyField(through='student.ProgrammeChoice', to='student.Institution'),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_enrolled', models.DateTimeField(auto_now_add=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.institution')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.programme')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'programme', 'institution')},
            },
        ),
    ]
