# Generated by Django 3.1.2 on 2020-10-21 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_programmechoice_cutoff_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='date_enrolled',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
