# Generated by Django 3.1.2 on 2020-10-21 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20201021_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programme',
            name='cutoff_points',
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='Student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
    ]
