# Generated by Django 3.1.2 on 2020-10-22 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_student_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Instutution',
            new_name='Institution',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='instutution',
            new_name='institution',
        ),
        migrations.RenameField(
            model_name='programmechoice',
            old_name='instutution',
            new_name='institution',
        ),
        migrations.RemoveField(
            model_name='programme',
            name='instutution',
        ),
        migrations.AddField(
            model_name='programme',
            name='institution',
            field=models.ManyToManyField(through='student.ProgrammeChoice', to='student.Institution'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('Student', 'programme', 'institution')},
        ),
    ]
